import StarsCanvas from '@/components/shared/StarBack';
import '../globals.css'
export const metadata = {
  title: 'Nasa Space App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased bg-black  overflow-x-hidden`}
      >
        {/* <StarsCanvas /> */}
        {children}
      </body>
    </html>
  );
}
